# Generated by Django 5.1.5 on 2025-01-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=8)),
                ('birth_day', models.DateField()),
                ('passport_id', models.CharField(max_length=7, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
